### ISSUE TITLE
Inconsistency in selecting .env file and undocumented behavior for 'dev'

### ISSUE THREAD

**Issue by heidighunter** [erisanolasheni/custom-env#11]
After struggling with figuring out why my environment variables weren't present for NODE_ENV=dev, I looked into the code and learned the following:

- Despite explicitly setting NODE_ENV=dev, due to the special treatment of that environment specifier it loads _.env_ **first** if it is present. (I had both _.env_ and _.env.dev_.) I think this would be unexpected in most cases - more specification should usually take precedent over less specification.

- The documentation states a few times that if the environment is not specified, it is assumed to be development. This is not strictly true - if no environment is specified it attempts to load _.env_. (Full stop.) It doesn't necessarily imply anything about the runtime environment, just which file it will look for.

IMO it would be better to make the filename lookup consistent for all environment specifiers, so there are no 'surprise' special cases. Specifically, if the environment is 'dev', then _.env.dev_ is loaded if present. A nice fallback might be to look for _.env_ as a fallback for both the case where the environment is not specified (as currently) and for the case where the environment-specific file is not present (e.g. if env=dev and _.env.dev_ is not available, it tries to load _.env_ as a second priority).

**Comment by erisanolasheni** [comment]
Hi @heidighunter I've started working with this, will get it fixed!

**Comment by erisanolasheni** [comment]
Thanks @heidighunter , [Version 2](https://github.com/erisanolasheni/custom-env/releases) A new version is available,  this is now resolved. It now selects file consistently and falls back to `.env` configuration if not found.
