### ISSUE TITLE
Is there a way to re-require another env file?

### ISSUE THREAD

**Issue by wpitallo** [erisanolasheni/custom-env#12]
Is there a way to re-require another env file?

So for example:

require('custom-env').env('development')
//do some stuff

require('custom-env').env('local')
//do some stuff

**Comment by erisanolasheni** [comment]
Hello @wpitallo Please not that `custom-env` does not place restrictions on this, so you can use it. However, also understand that if the same key is being place in multiple configuration files, `custom-env` will only grab the first required configuration and ignore others.
In your case:
```env
require('custom-env').env('development')
//do some stuff

require('custom-env').env('local')
//do some stuff
```
If both configuration files have the PORT key, `process.env.PORT` will contain the value found in `.env.development` file.

Thanks.

**Comment by wpitallo** [comment]
Thank you :)
