### ISSUE TITLE
Example on Loading from the current environment

### ISSUE THREAD

**Issue by abdullahIsa** [erisanolasheni/custom-env#20]
Hello thanks for this but I am a bit confused on how to make the env automatically change if in production or development, i don't want to always be changing the value.

How to do so ?
require("custom-env").env("development"); // change based on current environment as cant do an if check since its at the top of file.

Thanks.

**Comment by jeremydein** [comment]
Using a environment file name .env.development

1. Firstly set your require to below - Removing development and adding true (boolean).
`require("custom-env").env(true);`

2. Set NODE_ENV to development. e.g. set NODE_ENV=development in your package.json

**Comment by abdullahIsa** [comment]
Update:
ended up using **cross-env** with **dotenv-flow** i think my mistake was i was i was adding **&&** after **NODE_ENV=production**
