### ISSUE TITLE
instanceof Array incorrectly returns false

### ISSUE THREAD

**Issue by andrussuitsu** [erisanolasheni/custom-env#5]
main.js: 76
if (filesInDir instanceof Array && filesInDir.length > 0)

instanceof returns false even if filesInDir is actually a nonempty array. Use instead:
if (Array.isArray(filesInDir) && filesInDir.length > 0)

This works correctly.

**Comment by erisanolasheni** [comment]
Hello thanks for this, this has been corrected from this repo for long, but has not really being pushed to the npm repo, please clone or download this repo to use the latest version. I will also be update the npm version soon!

Thanks!
