### ISSUE TITLE
after goes to 1.0.2, my configuration not work anymore

### ISSUE THREAD

**Issue by hailincai** [erisanolasheni/custom-env#8]
After goes to 1.0.2 version, the property value like 'abc$2011' can be loaded correctly, the value been loaded will only have "abc". Is this supposed to work in this way?

At least at 1.0.0, ther is no such kind of issue.

**Comment by erisanolasheni** [comment]
@hailincai please elaborate more on your issue, you may specify a code line, full error code, screenshot or step by step guide how to reproduce this error.

**Comment by erisanolasheni** [comment]
@hailincai I will be closing this issue as I did not here back from you. If you still have problems, please re-open a new issue.
