### ISSUE TITLE
this library should have a default env config for fallback

### ISSUE THREAD

**Issue by EhsanSarshar** [erisanolasheni/custom-env#9]
if no match found for current NODE_ENV it should simply load a default .env.default file

**Comment by erisanolasheni** [comment]
Alright, we will work on that, thanks!

**Comment by heidighunter** [comment]
Agree, but I think using plain _.env_ as the default fallback would be preferable to having a special designator. See my comments on issue #11

**Comment by erisanolasheni** [comment]
Thanks @EhsanSarshar  , [Version 2](https://github.com/erisanolasheni/custom-env/releases) A new version is available. It now fall back to `.env` configuration if not found.

Thanks again!
